### ISSUE TITLE
Chloropeth Map in second tab

### ISSUE THREAD

**Issue by revathyponn** [UBC-MDS/dsci532-group19-buildingpermits#26]
-Could have a second chloropleth map with different boundaries (i.e. hexgrid, postal code areas, etc)
-Map should be full page
-No pan should be enabled
-Zoom to extent of all polygons
-Have the dropdown input overlay on top of the map
- to explore the having another chart if time permits

**Comment by spencergerlach** [comment]
These updates are detailed updates that can be addressed in a later milestone
